### ISSUE TITLE
command 'vanilla-bloc.new-bloc-base' not found

### ISSUE THREAD

**Issue by Sun3** [Allan-Nava/Vanilla-BLoC-Extension#1]
I installed the Vanilla-BLoC-Extension in Visual Studio Code but when I try to run any of the commands to create a BLoC I always receive the following error:

Error:
```
Command 'Vanilla BLoC: New Vanilla BLoC Base' resulted in an error (command 'vanilla-bloc.new-bloc-base' not found)
```

Any ideas?
Thank you.

**Comment by Allan-Nava** [comment]
Is still in developing! I'm trying to implement this examples: https://www.didierboelens.com/2018/12/reactive-programming-streams-bloc-practical-use-cases/

If you want to help ☺️

**Comment by Sun3** [comment]
Got it 👍

**Comment by Allan-Nava** [comment]
> Got it 👍

I have implement the new version, now it works?
You want to initialize your project with this flow: 
https://www.didierboelens.com/2018/12/reactive-programming-streams-bloc-practical-use-cases/

**Comment by Sun3** [comment]
I just reinstalled the new version of the plugin but it still gives the same error when trying to create a new BLoC.

**Comment by Allan-Nava** [comment]
> I just reinstalled the new version of the plugin but it still gives the same error when trying to create a new BLoC.

Mmh now i'm trying to debug! Wanna help me?

**Comment by Allan-Nava** [comment]
@Sun3 with this commit maybe it will be fixed : https://github.com/Allan-Nava/Vanilla-BLoC-Extension/commit/194678a4002eebc8cf694f5f9d641e388a4e63c7

Let me know

**Comment by Sun3** [comment]
Yes, I will help to debug.

**Comment by Allan-Nava** [comment]
> Yes, I will help to debug.

Perfect! Can I write u in private?

**Comment by Sun3** [comment]
Sure...

**Comment by Allan-Nava** [comment]
> Sure...

Have u tried the new version? And What do u think the extension miss?

**Comment by Allan-Nava** [comment]
I tried now in debug, and it seems work. 
<img width="1030" alt="Screenshot 2020-05-26 at 15 06 44" src="https://user-images.githubusercontent.com/22498435/82904416-bf1a3a80-9f62-11ea-81f7-909c151eb175.png">

Now i will publish the new version.

**Comment by Sun3** [comment]
I uninstalled and reinstalled but same error. I have attached a screenshot.

![Vanilla-Bloc-Errors](https://user-images.githubusercontent.com/4562374/82926720-9c315b80-9f4d-11ea-8d35-06a03aebf4dd.png)

**Comment by Allan-Nava** [comment]
> I uninstalled and reinstalled but same error. I have attached a screenshot.
> 
> ![Vanilla-Bloc-Errors](https://user-images.githubusercontent.com/4562374/82926720-9c315b80-9f4d-11ea-8d35-06a03aebf4dd.png)

I have tried in debug mode and it works! But I have added in the package.json and extension.ts correctly, I think.

**Comment by Allan-Nava** [comment]
> I uninstalled and reinstalled but same error. I have attached a screenshot.
> 
> ![Vanilla-Bloc-Errors](https://user-images.githubusercontent.com/4562374/82926720-9c315b80-9f4d-11ea-8d35-06a03aebf4dd.png)

I have create the telegram group: https://t.me/vanilla_bloc_ext

**Comment by Allan-Nava** [comment]
@Sun3 it fixed with this commit: https://github.com/Allan-Nava/Vanilla-BLoC-Extension/commit/06e65e30375e001595c0b5a444ba74f57ae81649

**Comment by Sun3** [comment]
Looking great. I just tested and they all worked except for the Create New Bloc option. I have placed the error screnshot:


![Create-bloc-error](https://user-images.githubusercontent.com/4562374/83062692-0c62de80-a02d-11ea-88e1-f07af01a48a3.png)

**Comment by Allan-Nava** [comment]
Okay now I will debug this problem. But any suggestion for the creation of custom bloc base? @Sun3

**Comment by Allan-Nava** [comment]
> Looking great. I just tested and they all worked except for the Create New Bloc option. I have placed the error screnshot:
> 
> ![Create-bloc-error](https://user-images.githubusercontent.com/4562374/83062692-0c62de80-a02d-11ea-88e1-f07af01a48a3.png)

Fixed with new commit https://github.com/Allan-Nava/Vanilla-BLoC-Extension/commit/662db16b9a21d0a4b706b3854e62aade28efac1f @Sun3
